"""init

Revision ID: 231e38291807
Revises: 
Create Date: 2026-02-18 16:55:29.564861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '231e38291807'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('my_grade', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('my_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('wishlist_card', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               nullable=True)
        batch_op.alter_column('number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist_card', schema=None) as batch_op:
        batch_op.alter_column('number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('pokemon_card', schema=None) as batch_op:
        batch_op.alter_column('number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('my_price')
        batch_op.drop_column('my_grade')

    # ### end Alembic commands ###
